import chess

board = chess.Board()

board.push_san("e4")
print(board)
print("\n")
board.push_san("c5")
print(board)
print("\n")
board.push_san("Nf3")
print(board)
print("\n")
board.push_san("d6")
print(board)
print("\n")
board.push_san("d4")
print(board)
print("\n")
board.push_san("c5xd4")
print(board)
print("\n")
board.push_san("Nd4")
print(board)
print("\n")
board.push_san("Nf6")
print(board)
print("\n")
board.push_san("Nc3")
print(board)